name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:   
  build:
    name: Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
    
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        swift-version: ["5"]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: swift-actions/setup-swift@150267bf6ba01f9d942a4bd55aa2f35ba586767d
      with:
        swift-version: ${{ matrix.swift-version }}
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
